# Generated by Django 5.2 on 2025-04-26 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='prefix',
            field=models.CharField(default=1, max_length=10, verbose_name='Prefixo do Código'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='produto',
            name='material_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Código do Produto'),
        ),
    ]
