# Generated by Django 5.2 on 2025-04-26 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_category_prefix_alter_produto_material_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='value',
        ),
        migrations.AddField(
            model_name='price',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='purchase_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Valor de Compra'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='sale_value',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Valor de Revenda'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='price',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
    ]
