# Generated by Django 5.2 on 2025-04-27 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0003_remove_price_value_price_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='total_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor Total'),
        ),
    ]
