# Generated by Django 5.2 on 2025-04-28 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0004_sale_total_value'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'verbose_name': 'Preço', 'verbose_name_plural': 'Preços'},
        ),
        migrations.AlterModelOptions(
            name='sale',
            options={'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterModelOptions(
            name='salesitem',
            options={'verbose_name': 'Item Vendido', 'verbose_name_plural': 'Itens Vendidos'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'Estoque', 'verbose_name_plural': 'Estoques'},
        ),
    ]
