# Generated by Django 5.2 on 2025-04-28 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sale_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Revenda')),
                ('purchase_value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Compra')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price', to='products.produto', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Preço',
                'verbose_name_plural': 'Preços',
            },
        ),
    ]
