"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-iinbqzm^e##__4uzb==%joyi(#z1iein4-a%kw!3ac-+0o9p44'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'jazzmin',

    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'stock',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'

TIME_ZONE = 'America/Sao_Paulo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

JAZZMIN_SETTINGS = {
    "site_title": "Estoque & Vendas",  # Título da aba do navegador
    "site_header": "Gestão de Estoque e Vendas",  # Cabeçalho do Admin
    "site_brand": "Estoque & Vendas",  # Marca do site
    "welcome_sign": "Bem-vindo(a) ao Painel de Controle 💖",
    "login_message": "",  # Mensagem que aparece na tela de login
    "copyright": "© 2025 Henrique LTDA",

    # Estética geral
    "show_sidebar": True,
    "navigation_expanded": False,  # Menu inicia colapsado para mais espaço
    "hide_apps": [],
    "hide_models": [],

    # Tema que combina melhor com rosa
    "theme": "pulse",

    # Configurações avançadas de navegação
    "order_with_respect_to": ["vendas", "produtos", "estoques", "auth"],



    # Ícones para o menu
    "icons": {
        "auth": "fas fa-user-lock",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",

        "products": "fas fa-cube",
        "products.Product": "fas fa-box",
        "products.Category": "fas fa-cogs",
        "sales": "fas fa-cash-register",
        "sales.sale": "fas fa-cart-arrow-down",
        "sales.itemvenda": "fas fa-receipt",
        "Customers": "fas fa-users",
        "customers.Customer": "fas fa-user-friends",
        "stocks": "fas fa-warehouse",
        "stocks.Stock": "fas fa-boxes",
        "prices": "fas fa-tag",
        "prices.Price": "fas fa-dollar-sign"
},
    "default_icon_parents": "fas fa-folder-open",
    "default_icon_children": "fas fa-leaf",

    # Configurações de formulário
    "changeform_format": "horizontal_tabs",
    "changeform_format_overrides": {
        "auth.user": "collapsible",
        "products.product": "horizontal_tabs",
        "sales.sale": "horizontal_tabs",
    },

    # Melhorias nas listas/tabelas
    "list_per_page": 20,  # Itens por página na lista
    "search_fields": {
        "auth.User": ["username", "first_name", "last_name", "email"],
        "products.product": ["nome", "codigo", "descricao"],
        "sales.sale": ["cliente__nome", "numero"],
    },

    # Configurações de ações
    "actions_sticky_top": True,  # Mantém botões de ação visíveis ao rolar
    "show_close_button": True,  # Botão de fechar em modais
    "related_modal_active": True,  # Abre formulários relacionados em modal

    # Filtros
    "filters_sticky_top": True,  # Mantém filtros visíveis ao rolar
    "use_select2": True,  # Ativa select2 para campos de seleção melhorados
    "use_select2_for_related": True,  # Ativa select2 para campos relacionados

    # Campos de pesquisa
    "search_model": ["auth.User", "productos.produto", "vendas.venda"],

    # CSS personalizado
    "custom_css": "custom_admin.css",

    # Logo (opcional)
    "site_logo": None,
    "site_logo_classes": "img-circle elevation-3",
    "site_icon": None,
}

# Configuração de cores personalizadas
JAZZMIN_UI_TWEAKS = {
    "navbar_small_text": False,
    "footer_small_text": False,
    "body_small_text": False,
    "brand_small_text": False,
    "brand_colour": "navbar-pink",
    "accent": "accent-pink",
    "navbar": "navbar-pink navbar-dark",
    "no_navbar_border": True,
    "navbar_fixed": True,
    "layout_boxed": False,
    "footer_fixed": False,
    "sidebar_fixed": True,
    "sidebar": "sidebar-light-pink",
    "sidebar_nav_small_text": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": True,
    "sidebar_nav_compact_style": True,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "default",
    "dark_mode_theme": None,
    "button_classes": {
        "primary": "btn-pink",  # Trocado para botões coloridos em rosa
        "secondary": "btn-outline-secondary",
        "info": "btn-info",
        "warning": "btn-warning",
        "danger": "btn-danger",
        "success": "btn-pink"
    }
}

