# Generated by Django 5.2 on 2025-05-02 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='salesitem',
            options={'verbose_name': 'Saida Estoque', 'verbose_name_plural': 'Saidas Estoque'},
        ),
    ]
